
- name: Importing specific distro variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars
    - always

- name: Default mpm module based on EL distribution (default)
  block:
    - name: Setting default mpm module to prefork for RHEL 7 and below
      set_fact:
        httpd_mpm_module: mpm_prefork
      when:
        - httpd_mpm_module is not defined
        - ansible_distribution_major_version|int < 8

    - name: Setting default mpm module to event for RHEL 8 and beyond
      set_fact:
        httpd_mpm_module: mpm_event
      when:
        - httpd_mpm_module is not defined
        - ansible_distribution_major_version|int > 7
  tags:
    - vars
    - always
    - mpm

- name: Ensuring httpd is installed
  yum:
    name: httpd
    state: installed

- name: Systemd snippet directory
  file:
    path: /etc/systemd/system/httpd.service.d/
    state: directory

- name: Default basic config
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - 01_common.conf
    - welcome.conf
  notify: restart_httpd

- name: Configuring logrotate for httpd process
  template:
    src: "templates/logrotate.d/{{ item }}.j2"
    dest: "/etc/logrotate.d/{{ item }}"
  with_items:
    - httpd
  tags:
    - logrotate

- name: Distribute default CentOS header files
  copy:
    src: "{{ item }}"
    dest: /var/www/
  with_items:
    - centos
    - centos-design

- name: Creating CentOS default header
  template:
    src: header.html.j2
    dest: /var/www/centos-design/header-{{ httpd_html_autoindex_title | lower | replace(" ","-") }}.html
    mode: 0644
  vars:
    page: "{{ httpd_common_autoindex }}"

- name: Creating CentOS default footer
  template:
    src: common/page-footer.html.j2
    dest: /var/www/centos-design/footer.html
    mode: 0644
  vars:
    page:
      with_social: true
      with_datatables: false
      with_highlight: false
      with_shortcuts: false
      with_finale: true
      with_sponsors: false
      with_copyright: true

- name: Create directory for common resources
  file:
    path: "{{ httpd_common_directory }}"
    state: directory

- name: Create page not found file
  template:
    src: "common/page.html.j2"
    dest: "{{ httpd_common_directory }}/404.html"
  vars:
    page:
      title: "404"
      title_lead: "Page not found."
      with_manifestation: ""
      with_social: true
      with_datatables: false
      with_highlight: false
      with_shortcuts: false
      with_finale: true
      with_sponsors: false
      with_copyright: true
      with_content:
        - element: p
          element_content: >-
            The requested page could not be found.
        - element: p
          element_content: >-
            This happens when the page has been moved, removed, or had its name
            and address changed. It might otherwise be temporarily unavailable
            for technical reasons.

- name: Ensuring httpd service is started
  service:
    name: httpd
    state: started
    enabled: true

- name: Opening up httpd rule
  include_role:
    name: iptables
    tasks_from: custom-policy
  vars:
    iptables_policy_name: httpd
    iptables_protocol: tcp
    iptables_port: "80"
    iptables_source: "0.0.0.0/0"
  when: httpd_public
  tags:
    - iptables

- name: Opening up httpd rule over ipv6
  include_role:
    name: iptables
    tasks_from: custom-policy-ipv6
  vars:
    iptables_policy_name: httpd
    iptables_protocol: tcp
    iptables_port: "80"
    iptables_source: "::/0"
  when: httpd_public
  tags:
    - iptables

- include_tasks: tls.yml
  when: httpd_tls

- block:
    - name: Configuring httpd mpm mode
      template:
        src: 00-mpm.conf.j2
        dest: /etc/httpd/conf.modules.d/00-mpm.conf
        mode: '0644'
        owner: root
      notify:
        - restart_httpd

    - name: Configuring correct selinux boolean for mpm
      seboolean:
        name: httpd_graceful_shutdown
        state: True
        persistent: True
  tags:
    - mpm

- block:
    - name: Ensure we have mod_qos pkg installed
      yum:
        name: mod_qos
        state: latest

    - name: Distributing mod_qos config
      template:
        src: 01_qos.conf.j2
        dest: /etc/httpd/conf.d/01_qos.conf
      notify:
        reload_httpd
  when: httpd_mod_qos
  tags:
    - qos

- block:
    - name: Configuring agent in Zabbix server
      include_role:
        name: zabbix-server
        tasks_from: agent_config
      vars:
        zabbix_templates: "{{ httpd_zabbix_templates }}"
        zabbix_groups: "{{ httpd_zabbix_groups }}"
  delegate_to: "{{ zabbix_api_srv }}"
  tags:
    - monitoring
  when:
    - zabbix_api_srv is defined
    - zabbix_api_srv != 'None'
    - zabbix_monitoring
