- name: Ensuring we have repo defined
  yum:
    name: centos-release-scl
    state: installed
  tags:
    - php 

- name: Ensuring we have php from SCL installed
  yum:
    name: ['rh-php{{ scl_php_ver }}', 'rh-php{{ scl_php_ver }}-php-xml', 'rh-php{{ scl_php_ver }}-php-xmlrpc', 'rh-php{{ scl_php_ver }}-php-mbstring', 'rh-php{{ scl_php_ver }}-php-gd', 'rh-php{{ scl_php_ver }}-php-soap', 'rh-php{{ scl_php_ver }}-php-mysqlnd', 'rh-php{{ scl_php_ver }}-php-fpm']
    state: latest
  tags:
    - php 

- name: Enabling PHP FPM
  service:
    name: rh-php{{ scl_php_ver }}-php-fpm
    state: started
    enabled: True
  tags:
    - php 
-
- name: Adding php fpm to httpd conf
  template:
    src: scl-php-fpm.conf.j2
    dest: /etc/httpd/conf.d/php-fpm.conf
  notify: restart_httpd
  tags:
    - php 

