- name: Ensuring we have repo defined
  yum:
    name: centos-release-scl
    state: installed

- name: Ensuring we have php from SCL installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - rh-php71
    - rh-php71-php-xml
    - rh-php71-php-mbstring 
    - rh-php71-php-gd 
    - rh-php71-php-soap 
    - rh-php71-php-mysqlnd 
    - rh-php71-php-fpm

- name: Enabling PHP FPM
  service:
    name: rh-php71-php-fpm
    state: started
    enabled: True

- name: Adding php fpm to httpd conf
  template:
    src: scl-php-fpm.conf.j2
    dest: /etc/httpd/conf.d/php-fpm.conf
  notify: restart_httpd  
