- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ httpd_www_hostname }}"

- name: Merging admins and local users list
  set_fact:
    people_users: "{{ admins_list + local_users_list }}"

- name: Ensuring we have public space for users
  file:
    path: "/home/{{ item.login_name }}/public_html"
    state: directory
    owner: "{{ item.login_name }}"
    group: "{{ item.login_name }}"
    mode: 0775
    setype: httpd_user_content_t
  with_items: "{{ people_users }}" 
  loop_control:
    label : "{{ item.login_name }}"

- name: Ensuring we have correct perms for httpd to read 
  file:
    path: "/home/{{ item.login_name }}"
    state: directory
    owner: "{{ item.login_name }}"
    group: "{{ item.login_name }}"
    mode: 0711
  with_items: "{{ people_users }}" 
  loop_control:
    label : "{{ item.login_name }}"

- name: Creating DocumentRoot for people vhost
  file:
    path: "{{ httpd_autoindex_people_directory }}"
    state: directory
    mode: 0755

- name: Creating autoindex directory structure
  ansible.builtin.file:
    path: "{{ httpd_autoindex_directory }}/{{ item.template }}-{{ item.title | replace(' ', '-') | lower }}"
    state: directory
    mode: "755"
  loop: "{{ httpd_autoindex_pages }}"

- name: Creating page not found file
  template:
    src: "autoindex/404.html.j2"
    dest: "{{ httpd_autoindex_directory }}/404.html"

- name: Creating people index file
  template:
    src: "autoindex/header-centos-people-index.html.j2"
    dest: "{{ httpd_autoindex_people_directory }}/index.html"

- name: Creating people HEADER.html files
  template:
    src: "autoindex/header-{{ item.template }}.html.j2"
    dest: "{{ httpd_autoindex_directory }}/{{ item.template }}-{{ item.title | replace(' ', '-') | lower }}/HEADER.html"
  when: item.template == "centos-people"
  loop: "{{ httpd_autoindex_pages }}"

- name: Creating HEADER.html files
  template:
    src: "autoindex/header-{{ item.template }}.html.j2"
    dest: "{{ httpd_autoindex_directory }}/{{ item.template }}-{{ item.title | replace(' ', '-') | lower }}/HEADER.html"
  when: item.template == "centos"
  loop: "{{ httpd_autoindex_pages }}"

- name: Creating README.html
  template:
    src: "autoindex/footer.html.j2"
    dest: "{{ httpd_autoindex_directory }}/README.html"

- name: Configuring httpd vhost for people
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - userdir.conf
    - 02_people.conf
    - ssl-people.conf
  notify:
    - restart_httpd

- name: Enabling needed selinux booleans
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: on
  with_items:
    - httpd_enable_homedirs
    - httpd_read_user_content

- name: Opening up sshd port for people access
  include_role:
    name: iptables
    tasks_from: "{{ item }}"
  vars:
    iptables_policy_name: sshd-people
    iptables_protocol: tcp
    iptables_port: "22"
  with_items:
    - custom-policy-ipv6
    - custom-policy
    
