- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: console.qa.centos.org

- name: Configuring httpd vhost for people
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - userdir.conf
    - 02_console-qa.conf
    - ssl-console-qa.conf
  notify:
    - restart_httpd

- name: Enabling needed selinux booleans
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: on
  with_items:
    - httpd_can_network_connect

    
