- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: people.centos.org

- name: Merging admins and local users list
  set_fact:
    people_users: "{{ admins_list + local_users_list }}"

- name: Ensuring we have public space for users
  file:
    path: "/home/{{ item.login_name }}/public_html"
    state: directory
    owner: "{{ item.login_name }}"
    group: "{{ item.login_name }}"
    mode: 0775
    setype: httpd_user_content_t
  with_items: "{{ people_users }}" 
  loop_control:
    label : "{{ item.login_name }}"

- name: Ensuring we have correct perms for httpd to read 
  file:
    path: "/home/{{ item.login_name }}"
    state: directory
    owner: "{{ item.login_name }}"
    group: "{{ item.login_name }}"
    mode: 0711
  with_items: "{{ people_users }}" 
  loop_control:
    label : "{{ item.login_name }}"

- name: Creating DocumentRoot for people vhost
  file:
    path: /var/www/people
    state: directory
    mode: 0755

- name: Creating users list for people vhost
  template:
    src: people-users.j2
    dest: /var/www/people/users.html
    mode: 0644
  register: user_list_html

- name: Creating index.html for people vhosts
  shell: cat /var/www/centos-design/header-{{ httpd_html_autoindex_title | lower | replace(" ","-") }}.html /var/www/people/users.html /var/www/centos-design/footer.html > /var/www/people/index.html
  when: user_list_html is changed

- name: Configuring httpd vhost for people
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - userdir.conf
    - 02_people.conf
    - ssl-people.conf
  notify:
    - restart_httpd

- name: Enabling needed selinux booleans
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: on
  with_items:
    - httpd_enable_homedirs
    - httpd_read_user_content

- name: Opening up sshd port for people access
  include_role:
    name: iptables
    tasks_from: "{{ item }}"
  vars:
    iptables_policy_name: sshd-people
    iptables_protocol: tcp
    iptables_port: "22"
  with_items:
    - custom-policy-ipv6
    - custom-policy
    
