# This task is more or less equivalent to vhost-www except that it also renders (through podman) website content
# Once done, it will push to other nodes rendered website (through specific keys allowed on web nodes

- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: www.stg.centos.org

- name: Adding specific webcontent user[s]
  user: 
    name: '{{ item.name }}' 
    state: present 
    comment: "CentOS Web content user for branch {{ item.branch }}"
    groups: centos
    append: True
  with_items: "{{ httpd_www_local_users }}"  
  

- name: Ensuring we have a DocumentRoot
  file:
    path: "/var/www/centos_website/"
    state: directory
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: 0775
  with_items: "{{ httpd_www_local_users }}"  


- name: Configuring httpd vhost for www
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - 02_vhost-www.conf
    - ssl-vhost-www.conf
  notify:
    - reload_httpd
  tags:
    - config

- name: Install some tools to render website locally
  yum:
    name: 
      - podman
      - git
      - python3-feedparser
      - python3
    state: installed
  tags:
    - pkgs

- name: Enabling needed selinux booleans
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: on
  with_items:
    - httpd_can_network_connect

- name: rss2json util
  template:
    src: www/rss2json.py
    dest: /usr/libexec/centos/rss2json.py
    mode: 0755
    owner: root
  tags:
    - script

- name: Wrapper tool to build website
  template:
    src: www/centos_website.j2
    dest: /usr/libexec/centos/centos_website
    mode: 0755
    owner: root
  register: centos_website_script
  tags:
    - script

- name: Init podman containers
  command: "/usr/libexec/centos/centos_website init {{ item.branch }}"
  when: centos_website_script is changed
  become_user: "{{ item.name }}"
  with_items: "{{ httpd_www_local_users }}"
  tags:
    - script

#- name: Cron to compare upstream git
#  cron:
#    name: Build website from git
#    job: "/usr/libexec/centos/centos_website build {{ item.branch }}"
#    minute: "*/2"
#    user: "{{ item.name }}"
#  with_items: "{{ httpd_www_local_users }}"
#  tags:
#    - cron

#- name: Cron to refresh external content for website
#  cron:
#    name: Refreshing csv and rss files for website
#    job: "/usr/libexec/centos/centos_website refresh {{ item.branch }}"
#    minute: "25"
#    user: "{{ item.name }}"
#  with_items: "{{ httpd_www_local_users }}"
#  tags:
#    - cron

- block: 
    - name: Configuring agent in Zabbix server
      include_role:
        name: zabbix-server
        tasks_from: agent_config
      vars:
        zabbix_templates: "{{ httpd_stg_zabbix_templates }}"
        zabbix_groups: "{{ httpd_zabbix_groups }}"
  delegate_to: "{{ zabbix_api_srv }}"  
  tags:
    - monitoring
  when: zabbix_api_srv is defined and zabbix_api_srv != 'None'

