- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ httpd_people_hostname }}"

- name: Merging admins and local users list
  set_fact:
    people_users: "{{ admins_list + local_users_list }}"

- name: Ensuring we have public space for users
  file:
    path: "/home/{{ item.login_name }}/public_html"
    state: directory
    owner: "{{ item.login_name }}"
    group: "{{ item.login_name }}"
    mode: 0775
    setype: httpd_user_content_t
  with_items: "{{ people_users }}"
  loop_control:
    label : "{{ item.login_name }}"

- name: Ensuring we have correct perms for httpd to read
  file:
    path: "/home/{{ item.login_name }}"
    state: directory
    owner: "{{ item.login_name }}"
    group: "{{ item.login_name }}"
    mode: 0711
  with_items: "{{ people_users }}"
  loop_control:
    label : "{{ item.login_name }}"

- name: Creating DocumentRoot for people vhost
  file:
    path: "{{ httpd_people_dirname }}"
    state: directory
    mode: 0755

- name: Creating index.html for people vhosts
  template:
    src: people-users.j2
    dest: "{{ httpd_people_dirname }}/index.html"
    mode: 0644
  vars:
    page:
      title: People of CentOS
      title_lead: |
        This is an area where the CentOS Developers and allowed contributors
        can make test files and other things available that are not yet part of
        CentOS. Some items here will make it into CentOS, CentOS Extras and/or
        CentOS Plus ... while other things may not.
      with_manifestation: People
      with_social: true
      with_datatables: false
      with_highlight: false
      with_shortcuts: false
      with_finale: true
      with_sponsors: false
      with_copyright: true
      with_content:
        - element: p
          element_class: alert alert-warning
          element_content: >-
            <strong>Caution:</strong> Use anything here at your own risk!
        - element: p
          element_content: >-
            The following users currently have areas on people.centos.org:
            (sorted by First name)

- name: Creating HEADER files for people
  template:
    src: common/page-header-user.html.j2
    dest: "{{ httpd_people_dirname }}/HEADER-{{ item.login_name }}.html"
    mode: 0644
  with_items: "{{ people_users }}"
  vars:
    page:
      title: "{{ item.login_name }}"
      title_lead: "{{ item.full_name }}"
      with_manifestation: People
      with_content: []

- name: Creating FOOTER file for people
  template:
    src: common/page-footer.html.j2
    dest: "{{ httpd_people_dirname }}/FOOTER.html"
    mode: 0644
  vars:
    page:
      with_social: true
      with_datatables: false
      with_highlight: false
      with_shortcuts: false
      with_finale: true
      with_sponsors: false
      with_copyright: true

- name: Configuring httpd vhost for people
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - userdir.conf
    - 02_people.conf
    - ssl-people.conf
  notify:
    - restart_httpd

- name: Enabling needed selinux booleans
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: on
  with_items:
    - httpd_enable_homedirs
    - httpd_read_user_content

- name: Opening up sshd port for people access
  include_role:
    name: iptables
    tasks_from: "{{ item }}"
  vars:
    iptables_policy_name: sshd-people
    iptables_protocol: tcp
    iptables_port: "22"
  with_items:
    - custom-policy-ipv6
    - custom-policy
