# This task can be included and will parse the httpd_vhost_shared_list
# Example:
# httpd_vhost_shared_list:
#   - name: test
#     fqdn: test.domain.com
#     path: /srv/test
#   - name: restricted
#     fqdn: test2.domain.com
#     path: /srv/test2
#     acl:
#       - 192.168.1.0/23
#  

- name: vhost configs
  template:
    src: 99_vhost-shared-dir.conf.j2
    dest: "/etc/httpd/conf.d/99_vhost_{{ item.name }}.conf"
    mode: 0644
  with_items: "{{ httpd_vhost_shared_list }}"  
  notify:
    - restart_httpd

